spring:
  application:
    name: syntrivent-service-discovery
        
---

#spring:
#  profiles: prod

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9301/eureka
  instance:
    preferIpAddress: true
#       leaseRenewalIntervalInSeconds: 1
#       leaseExpirationDurationInSeconds: 2
    leaseRenewalIntervalInSeconds: 300
    leaseExpirationDurationInSeconds: 900
  server:
    enableSelfPreservation: false

---

